baseURL = "https://www.marcelocosta.tech/blog/"
languageCode = "en-us"
title = "Marcelo's Blog"
theme = "archie"

[pagination]
  pagerSize = 5

[params]
  mode = "dark"
  subtitle = "DevOps, Infra, and Automation from the trenches"
  googleAnalytics = ""  # disables the footer partial reference


[[params.social]]
  name = "github"
  url = "https://github.com/celo0"

